spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${gateway.user-service:http://localhost:8081/}
          predicates:
            - Path=/user-service/**
        - id: product-service
          uri: ${gateway.product-service:http://localhost:8082/}
          predicates:
            - Path=/product/**
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${eureka.server:http://localhost:8761/eureka/}
---
# Test profile that is not using the eureka server. ONLY FOR TESTING PURPOSES
spring:
  profiles: test
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false